// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "$61)BuSKtkJ~pitAkvb{":
            case "kalp":return img`
....................
....................
....................
....................
....................
....................
.......22...22......
......2322.2222.....
......232222222.....
......222222222.....
.......22222b2......
........222b2.......
.........222........
..........2.........
....................
....................
....................
....................
....................
....................
`;
            case "%f@G1%cK^!L${":
            case "bomba":return img`
....................
....................
....................
....................
....................
....................
.........bb.........
........cccc........
........cccc........
.........ff.........
.........cf.........
.........cc.........
........cccc........
.......cbbccc.......
.......cbcccc.......
.......cccccc.......
.......cccccf.......
........cfff........
....................
....................
`;
            case "!3L`an={ag]4,l!}oPF1":
            case "karakter":return img`
. . . . . . f f f f . . . . . . 
. . . . f f f 2 2 f f f . . . . 
. . . f f f 2 2 2 2 f f f . . . 
. . f f f e e e e e e f f f . . 
. . f f e 2 2 2 2 2 2 e e f . . 
. . f e 2 f f f f f f 2 e f . . 
. . f f f f e e e e f f f f . . 
. f f e f b f 4 4 f b f e f f . 
. f e e 4 1 f d d f 1 4 e e f . 
. . f e e d d d d d d e e f . . 
. . . f e e 4 4 4 4 e e f . . . 
. . e 4 f 2 2 2 2 2 2 f 4 e . . 
. . 4 d f 2 2 2 2 2 2 f d 4 . . 
. . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
